export const normalizeBlogText = (value = '') =>
    String(value || '').replace(/\s+/g, ' ').trim();

export const normalizeBlogSlug = (value = '') =>
    String(value || '')
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');

export const normalizeBlogBlocks = (contentBlocks = [], content = '') => {
    const blocks = Array.isArray(contentBlocks) ? contentBlocks : [];
    const normalized = blocks
        .map((block) => ({
            type: ['intro', 'heading', 'text', 'tip', 'conclusion'].includes(block?.type) ? block.type : 'text',
            text: normalizeBlogText(block?.text || '')
        }))
        .filter((block) => block.text);

    if (normalized.length > 0) return normalized;

    return String(content || '')
        .split(/\n{2,}/)
        .map((text, index, values) => ({
            type: index === 0 ? 'intro' : index === values.length - 1 ? 'conclusion' : 'text',
            text: normalizeBlogText(text)
        }))
        .filter((block) => block.text);
};

export const normalizeBlogForUi = (blog = {}) => {
    const blocks = normalizeBlogBlocks(blog.contentBlocks, blog.content);
    const content = normalizeBlogText(blog.content) || blocks.map((block) => block.text).join('\n\n');
    const summary = normalizeBlogText(blog.summary || blog.excerpt || '') || content.slice(0, 170);

    return {
        ...blog,
        _id: blog._id || blog.id || '',
        id: blog.id || blog._id || '',
        slug: normalizeBlogSlug(blog.slug || blog.title || ''),
        title: normalizeBlogText(blog.title || ''),
        summary,
        excerpt: summary,
        content,
        contentBlocks: blocks,
        featuredImage: blog.featuredImage || blog.image || '',
        image: blog.image || blog.featuredImage || '',
        category: normalizeBlogText(blog.category || 'General'),
        tags: Array.isArray(blog.tags) ? blog.tags.filter(Boolean) : [],
        author: normalizeBlogText(blog.author || 'DealSphere Editorial'),
        authorAvatar: String(blog.authorAvatar || blog.author || 'D').charAt(0).toUpperCase(),
        authorBio: normalizeBlogText(blog.authorBio || ''),
        date: blog.date || blog.publishedAt || blog.createdAt || '',
        publishedAt: blog.publishedAt || null,
        createdAt: blog.createdAt || null,
        updatedAt: blog.updatedAt || null,
        readTime: blog.readTime || `${Math.max(1, Math.ceil(content.split(/\s+/).filter(Boolean).length / 180))} min read`,
        seoTitle: normalizeBlogText(blog.seoTitle || blog.title || ''),
        seoDescription: normalizeBlogText(blog.seoDescription || summary),
        seoKeywords: Array.isArray(blog.seoKeywords) ? blog.seoKeywords.filter(Boolean) : [],
        status: blog.status || 'draft',
        featured: Boolean(blog.featured),
        autoGenerated: Boolean(blog.autoGenerated),
        sourceType: blog.sourceType || 'manual',
        relatedDeals: Array.isArray(blog.relatedDeals) ? blog.relatedDeals : [],
        relatedBlogs: Array.isArray(blog.relatedBlogs) ? blog.relatedBlogs : []
    };
};

export const formatBlogDate = (value = '') => {
    if (!value) return '';
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) return '';
    return parsed.toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'long',
        year: 'numeric'
    });
};
