import mongoose from 'mongoose';

const blogContentBlockSchema = new mongoose.Schema({
    type: {
        type: String,
        enum: ['intro', 'heading', 'text', 'tip', 'conclusion'],
        default: 'text'
    },
    text: {
        type: String,
        trim: true,
        default: ''
    }
}, { _id: false });

const relatedDealSchema = new mongoose.Schema({
    dealId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Deal'
    },
    title: {
        type: String,
        trim: true,
        default: ''
    },
    image: {
        type: String,
        trim: true,
        default: ''
    },
    productUrl: {
        type: String,
        trim: true,
        default: ''
    },
    affiliateLink: {
        type: String,
        trim: true,
        default: ''
    },
    store: {
        type: String,
        trim: true,
        default: ''
    },
    category: {
        type: String,
        trim: true,
        default: ''
    },
    dealPrice: {
        type: Number,
        default: 0
    },
    mrp: {
        type: Number,
        default: 0
    },
    discountPercent: {
        type: Number,
        default: 0
    }
}, { _id: false });

const blogSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
        trim: true
    },
    slug: {
        type: String,
        required: true,
        unique: true,
        index: true,
        trim: true
    },
    summary: {
        type: String,
        trim: true,
        default: ''
    },
    content: {
        type: String,
        trim: true,
        default: ''
    },
    contentBlocks: {
        type: [blogContentBlockSchema],
        default: []
    },
    featuredImage: {
        type: String,
        trim: true,
        default: ''
    },
    category: {
        type: String,
        trim: true,
        default: 'General'
    },
    tags: {
        type: [String],
        default: []
    },
    author: {
        type: String,
        trim: true,
        default: 'DealSphere Editorial'
    },
    authorBio: {
        type: String,
        trim: true,
        default: ''
    },
    publishedAt: {
        type: Date,
        default: null
    },
    seoTitle: {
        type: String,
        trim: true,
        default: ''
    },
    seoDescription: {
        type: String,
        trim: true,
        default: ''
    },
    seoKeywords: {
        type: [String],
        default: []
    },
    status: {
        type: String,
        enum: ['draft', 'published'],
        default: 'draft',
        index: true
    },
    featured: {
        type: Boolean,
        default: false
    },
    autoGenerated: {
        type: Boolean,
        default: false
    },
    sourceType: {
        type: String,
        enum: ['manual', 'automatic'],
        default: 'manual'
    },
    topicKey: {
        type: String,
        trim: true,
        default: '',
        index: true
    },
    relatedDeals: {
        type: [relatedDealSchema],
        default: []
    }
}, {
    timestamps: true
});

blogSchema.index({ status: 1, publishedAt: -1 });
blogSchema.index({ category: 1, status: 1 });
blogSchema.index({ tags: 1, status: 1 });

export default mongoose.model('Blog', blogSchema);
