import mongoose from 'mongoose';

const DealSchema = new mongoose.Schema({
    title: { type: String, required: true },
    originalTitle: { type: String },
    rawTitle: { type: String },
    displayTitle: { type: String },
    cardTitle: { type: String },
    image: { type: String, required: true },
    images: [{ type: String }],
    videos: [{ type: String }],
    price: { type: String, required: true },
    dealPrice: { type: Number, default: 0 },
    originalPrice: { type: String },
    mrp: { type: Number, default: 0 },
    discount: { type: String },
    discountPercent: { type: Number, default: 0 },
    rating: { type: Number, default: 0 },
    reviews: [{
        user: { type: String, required: true },
        rating: { type: Number, required: true },
        comment: { type: String, required: true },
        date: { type: Date, default: Date.now }
    }],
    store: { type: String, required: true },
    storeName: { type: String },
    category: { type: String },
    link: { type: String },
    productUrl: { type: String },
    canonicalProductUrl: { type: String, index: true },
    sourceProductId: { type: String, index: true },
    normalizedTitle: { type: String, index: true },
    duplicateKey: { type: String, index: true },
    variantGroupKey: { type: String, index: true },
    variantLabel: { type: String },
    variantType: { type: String },
    variants: [{
        id: { type: String },
        dealId: { type: String },
        variantKey: { type: String },
        groupKey: { type: String },
        label: { type: String },
        type: { type: String },
        title: { type: String },
        image: { type: String },
        images: [{ type: String }],
        price: { type: String },
        dealPrice: { type: Number, default: 0 },
        originalPrice: { type: String },
        mrp: { type: Number, default: 0 },
        discount: { type: String },
        discountPercent: { type: Number, default: 0 },
        productUrl: { type: String },
        link: { type: String },
        affiliateLink: { type: String },
        affiliateOverrideLink: { type: String },
        availability: { type: String },
        sourceProductId: { type: String }
    }],
    affiliateOverrideLink: { type: String },
    affiliateLink: { type: String },
    description: { type: String },
    featured: { type: Boolean, default: false },
    views: { type: Number, default: 0 },
    isExpired: { type: Boolean, default: false },
    createdAt: { type: Date, default: Date.now }
});

export default mongoose.model('Deal', DealSchema);
